# Generated by Django 5.2.8 on 2025-11-14 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiondetails',
            name='account',
        ),
        migrations.RemoveField(
            model_name='transactiondetails',
            name='user',
        ),
        migrations.DeleteModel(
            name='AccountDetails',
        ),
        migrations.DeleteModel(
            name='TransactionDetails',
        ),
    ]
